name: Reusable workflow A

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World A

jobs:
  call-workflow:
    uses: ./reusable-b.yml
    with:
      who-to-greet: ${{ inputs.who-to-greet }}
